const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Nike Fit Shirt",
      category: "shirts",
      image: "/images/p2.jpg",
      price: 105,
      countInStock: 20,
      brand: "Nike",
      rating: 3.5,
      numReviews: 11,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Adi Slim Shirt",
      category: "shirts",
      image: "/images/p3.jpg",
      price: 90,
      countInStock: 0,
      brand: "Adi",
      rating: 5,
      numReviews: 100,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Adi Fit Shirt",
      category: "shirts",
      image: "/images/p4.jpg",
      price: 125,
      countInStock: 15,
      brand: "Adi",
      rating: 3,
      numReviews: 15,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Lacoste Free Shirt",
      category: "shirts",
      image: "/images/p5.jpg",
      price: 80,
      countInStock: 55,
      brand: "Lacoste",
      rating: 5,
      numReviews: 20,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Nike Slim Pants",
      category: "shirts",
      image: "/images/p6.jpg",
      price: 110,
      countInStock: 19,
      brand: "Nike",
      rating: 4,
      numReviews: 14,
      description: "high quality product",
    },
  ],
};

export default data;
